name: Sync S3 Bucket, Invalidate Cloudfront

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-bucket:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Get AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Change directory to frontend
        run: |
          cd frontend
        
      - name: NPM install
        working-directory: ./frontend
        run: |
          npm ci

      - name: Run build
        working-directory: ./frontend
        run: |
          npm run build

      - name: Sync S3 bucket
        working-directory: ./frontend
        run: |
          aws s3 sync dist s3://${{ secrets.S3_BUCKET_NAME }}
      
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: "/index.html"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}